[default]
output_format = "table"
color = "auto"

[install]
editable = false
dry_run = false

[registry]
backup = true
max_backups = 5

[update]

[ui]
progress_style = "rich"
show_success = true
confirm_destructive = true

[logging]

[test]
key = "value"
